name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag nuonic/node-python-awscli:${GITHUB_REF#refs/heads/}

    - name: Tag Docker Image
#      if: github.ref == 'refs/heads/master'
      run: |
          export MAJOR=<major-version>
          export MINOR=<minor-version>
          export PATCH=<patch-version>
          export ACCOUNT=<docker-account>
          export NAME=<image-name>
          make tag

    - name: Log in to Docker Hub
#      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
#      if: github.ref == 'refs/heads/master'
      run: make push

