name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract branch name
      id: branch-name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      env:
        GITHUB_REF: ${{ github.ref }}

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: nuonic/node-python-awscli:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Push Docker image
      if: github.ref == 'refs/heads/master'
      run: make tag push
